spring.application.name=kante

jwt.secretkey=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
# Expiration de 24 heures en millisecondes
jwt.expiration=86400000 

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
# spring.data.mongodb.uri=mongodb+srv://dbUser:dbUserPassword@cluster0.rwynnnw.mongodb.net/scrum_platform?retryWrites=true&w=majority
spring.data.mongodb.uri=mongodb://localhost:27017/scrum_platform

upload.directory=./uploads

spring.mail.host=mail.kanteco.com
spring.mail.port=587
spring.mail.username=students-plateform@kanteco.com
spring.mail.password=NsJ7QngjhxhP3GzMJTs9
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true